--  회원테이블 -> 카테고리테이블 -> 카테고리 데이터 -> 상품테이블 -> 상품시퀀스
--  -> 공지사항테이블 -> 주문테이블 -> 리뷰테이블 -> 카트테이블 -> 공지사항시퀀스 -> 주문 시퀀스 
--  -> 리뷰시퀀스 -> ADMIN 회원가입후 주문데이터


-- 카트 테이블 
CREATE TABLE MYSHOP_CART(
	BID NUMBER PRIMARY KEY ,
    AMT NUMBER NOT NULL,
    ID VARCHAR2(15) NOT NULL,
    PID NUMBER NOT NULL,       --상품코드
    BDATE DATE,
 	CONSTRAINT FK_SHOP_CART_ID FOREIGN KEY(ID) REFERENCES MYSHOP_MEMBER(ID),
    CONSTRAINT FK_SHOP_CART_PID FOREIGN KEY(PID) REFERENCES MYSHOP_PRODUCT(PID)
);

--회원테이블 
CREATE TABLE MYSHOP_MEMBER(
    ID VARCHAR2(20) CONSTRAINT PK_SHOP_MEMBER_ID PRIMARY KEY,           --고객아이디
    PASS VARCHAR2(20) NOT NULL,                  --비밀번호
    NAME VARCHAR2(10) NOT NULL,                --이름
    EMAIL VARCHAR2(30) NOT NULL,               --이메일
    ZONECODE VARCHAR2(30) NOT NULL,            --우편번호
    HP VARCHAR2(10) CONSTRAINT SHOP_MEMBER_HP_CHECK CHECK(HP IN('SK','KT','LG')),  --통신사
    PNUMBER VARCHAR2(30) NOT NULL,   --휴대폰 번호
    ADDR     VARCHAR2(50) NOT NULL,  --주소
    BIRTH     VARCHAR2(15) NOT NULL, --생년월일
    MDATE  DATE,  --가입일
    GRADE VARCHAR2(8) CONSTRAINT SHOP_MEMBER_GRADE_EHECK CHECK(GRADE IN('BASIC','VIP','VVIP')), --등급
    EMAIL_CHECK CHAR(1) CONSTRAINT SHOP_MEMBER_EMAIL_CHECK CHECK(EMAIL_CHECK IN('Y','N')),  --이용약관 또는 이메일 수신여부          
    GENDER  CHAR(1) CONSTRAINT SHOP_MEMBER_GENDER_CHECK CHECK(GENDER IN('M','F'))     --성별             
);

--상품테이블 
CREATE TABLE MYSHOP_PRODUCT(
    PID NUMBER CONSTRAINT PK_SHOP_PRODUCT_PID PRIMARY KEY, --상품번호
    CATEGORY_ID NUMBER NOT NULL,       --카테고리
    PNAME VARCHAR2(100) NOT NULL,              --상품명
    BRAND VARCHAR2(40) NOT NULL,              --브랜드명
    PSIZE VARCHAR2(5) NOT NULL,                --상품 사이즈
    QUANTITY NUMBER NOT NULL,                 --수량
    PRICE NUMBER NOT NULL,                    --상품가격 
    DELIVERY_PRICE NUMBER NOT NULL,           --배송비
    REGDATE DATE DEFAULT SYSDATE,            --상품 등록일
    UPDATEDATE DATE DEFAULT SYSDATE,         --상품 수정일 
    RATING VARCHAR2(20),                      --상품 평점
    PDETAIL VARCHAR2(500),                    --상품 상세설명
    PFILE VARCHAR2(200) NOT NULL,              --상품이미지
    PSFILE VARCHAR2(200) NOT NULL,             --상품이미지
    CONSTRAINT FK_SHOP_CATEGORY_ID FOREIGN KEY(CATEGORY_ID) REFERENCES MYSHOP_CATEGORY(CATEGORY_ID)
);

-- 상품 시퀀스
CREATE SEQUENCE SEQU_SHOP_PRODUCT
    START WITH 1
    INCREMENT BY 1;

--리뷰테이블
CREATE TABLE MYSHOP_REVIEW(
    RID VARCHAR(15) CONSTRAINT PK_SHOP_REVIEW_RID PRIMARY KEY,
    PID NUMBER NOT NULL,                    --리뷰한 상품 아이디
    OID NUMBER NOT NULL,         --주문 아이디
    RWRITER VARCHAR2(15) NOT NULL,               --리뷰 작성자
    SCORE NUMBER(1),                        --사용자 평점
    RCONTENT VARCHAR2(300),                 --리뷰내용
    RFILE VARCHAR2(200),            
    RSFILE VARCHAR2(200),
    RECOM NUMBER(5) NOT NULL,               --추천 수
    RDATE DATE,                              --작성일
    CONSTRAINT FK_SHOP_review_OID FOREIGN KEY(OID) REFERENCES MYSHOP_ORDERS(OID),
    CONSTRAINT FK_SHOP_review_PID FOREIGN KEY(PID) REFERENCES MYSHOP_PRODUCT(PID)
    );

-- 카테고리테이블
CREATE TABLE MYSHOP_CATEGORY(
DEPT_LEVEL NUMBER NOT NULL,
CATEGORY_NM VARCHAR2(30) NOT NULL,
CATEGORY_ID NUMBER ,
CATEGORY_PARENT NUMBER,
PRIMARY KEY(CATEGORY_ID),
FOREIGN KEY(CATEGORY_PARENT) REFERENCES MYSHOP_CATEGORY(CATEGORY_ID)
);

--카테고리 데이터
INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID) VALUES(1,'여성',10000);
    INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(2,'의류',10100,10000);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'탑',10101,10100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'블라우스/셔츠',10102,10100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'원피스',10103,10100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'팬츠',10104,10100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'스커트',10105,10100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'스웨터',10106,10100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'코트/자켓',10107,10100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'언더웨어/라운지웨어',10108,10100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'스포츠웨어/아웃도어',10109,10100);
    INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(2,'슈즈',10200,10000);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'스니커즈',10201,10200);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'샌들/슬리퍼',10202,10200);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'로퍼',10203,10200);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'플랫',10204,10200);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'힐',10205,10200);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'드레스슈즈',10206,10200);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'부츠/워커',10207,10200);
    INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(2,'가방',10300,10000);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'크로스백',10301,10300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'클러치/파우치',10302,10300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'토트백',10303,10300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'숄더백',10304,10300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'백팩',10305,10300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'더블백',10306,10300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'러기지백',10307,10300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'기타',10308,10300);
    INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(2,'액세서리',10400,10000);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'지갑',10401,10400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'주얼리',10402,10400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'시계',10403,10400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'모자',10404,10400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'벨트',10405,10400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'키링',10406,10400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'아이웨어',10407,10400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'목도리/스카프',10408,10400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'장갑',10409,10400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'헤어액세서리',10410,10400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'손수건',10411,10400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'양말/스타킹',10412,10400);
INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID) VALUES(1,'남성',20000);
    INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(2,'의류',20100,20000);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'탑',20101,20100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'셔츠',20102,20100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'팬츠',20103,20100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'스웨터',20104,20100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'코트/자켓',20105,20100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'수트',20106,20100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'언더웨어/라운지웨어',20107,20100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'스포츠웨어/아웃도어',20108,20100);
    INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(2,'슈즈',20200,20000);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'스니커즈',20201,20200);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'샌들/슬리퍼',20202,20200);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'로퍼',20203,20200);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'드레스슈즈',20204,20200);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'부츠/워커',20205,20200);
    INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(2,'가방',20300,20000);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'크로스백',20301,20300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'클러치/파우치',20302,20300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'토트백',20303,20300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'브리프케이스',20304,20300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'백팩',20305,20300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'더블백',20306,20300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'러기지백',20307,20300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'기타',20308,20300);
    INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(2,'액세서리',20400,20000);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'지갑',20401,20400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'주얼리',20402,20400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'시계',20403,20400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'모자',20404,20400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'벨트/서스펜더',20405,20400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'키링',20406,20400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'아이웨어',20407,20400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'목도리/스카프',20408,20400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'장갑',20409,20400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'넥타이',20410,20400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'손수건',20411,20400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'양말',20412,20400);
INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID) VALUES(1,'키즈',30000);
    INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(2,'의류',30100,30000);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'탑',30101,30100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'팬츠',30102,30100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'스커트',30103,30100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'원피스',30104,30100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'세트',30105,30100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'바디수트',30106,30100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'코트/자켓',30107,30100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'언더웨어',30108,30100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'수영복',30109,30100);
    INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(2,'슈즈',30200,30000);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'스니커즈',30201,30200);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'샌들/슬리퍼',30202,30200);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'젤리슈즈',30203,30200);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'구드/플랫',30204,30200);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'부츠',30205,30200);
    INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(2,'엑세서리',30300,30000);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'모자',30301,30300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'목도리',30302,30300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'장갑',30303,30300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'가방',30304,30300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'헤어ACC',30305,30300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'양말/벨트',30306,30300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'패션소품',30307,30300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'시계',30308,30300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'기타 액세서리',30309,30300);
    INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(2,'토이',30400,30000);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'블록/게임완구',30401,30400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'로봇/블록완구',30402,30400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'승용/스포츠완구',30403,30400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'교육완구',30404,30400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'인형',30405,30400);
INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID) VALUES(1,'라이프',40000);
    INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(2,'뷰티',40100,40000);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'스킨케어/선케어',40101,40100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'바디케어',40102,40100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'메이크업',40103,40100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'향수',40104,40100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'미용기기/용품',40105,40100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'헤어케어',40106,40100);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'남성뷰티',40107,40100);
    INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(2,'테크',40200,40000);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'사운드',40201,40200);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'생활 가전',40202,40200);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'주방 가전',40203,40200);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'계절 가전',40204,40200);
    INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(2,'골프',40300,40000);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'여성 골프웨어',40301,40300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'남성 골프웨어',40302,40300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'골프화',40303,40300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'골프 잡화',40304,40300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'골프 가방',40305,40300);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'골프 용품',40306,40300);
    INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(2,'스포츠',40400,40000);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'아웃도어용품',40401,40400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'어반',40402,40400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'썸머',40403,40400);
        INSERT INTO MYSHOP_CATEGORY(DEPT_LEVEL,CATEGORY_NM,CATEGORY_ID,CATEGORY_PARENT) VALUES(3,'윈터',40404,40400);

--주문테이블
CREATE TABLE MYSHOP_ORDERS(
    OID NUMBER CONSTRAINT PK_SHOP_ORDER_OID PRIMARY KEY,   --주문번호
    PID NUMBER NOT NULL,                 --상품번호
    ID VARCHAR2(20) NOT NULL,            --회원아이디
    STATUS VARCHAR2(10) NOT NULL,        --주문상태
    ODATE DATE DEFAULT SYSDATE,                   --주문일자
    RECIPIENT_ZONECODE VARCHAR2(30) NOT NULL,     --배송지 우편번호
    RECIPIENT_ADDR VARCHAR2(50) NOT NULL,         --배송지 주소
    RECIPIENT_NAME VARCHAR2(10) NOT NULL,                --수령자 이름
    RECIPIENT_HP VARCHAR2(10) NOT NULL,                  --수령자 통신사
    RECIPIENT_PNUMBER VARCHAR2(20) NOT NULL,             --수령자 번호
    OADDR VARCHAR2(50) NOT NULL,               --배송지 주소
    QUANTITY NUMBER NOT NULL,                  --상품수량/개수
    PAYMENT VARCHAR2(10) NOT NULL,             --지불금액
    CONSTRAINT FK_SHOP_MEMBER_ID FOREIGN KEY(ID) REFERENCES MYSHOP_MEMBER(ID),
    CONSTRAINT FK_SHOP_PRODUCT_PID FOREIGN KEY(PID) REFERENCES MYSHOP_PRODUCT(PID)
);

--공지사항
    CREATE TABLE MYSHOP_NOTICE(
    NID         VARCHAR2(20)  CONSTRAINT PK_MYSHOP_NOTICE_NID PRIMARY KEY,
    NTITLE  VARCHAR2(200) NOT NULL,
    NCONTENT VARCHAR2(500),
    NCODE VARCHAR2(10),
    NFILE         VARCHAR2(200),
    NSFILE       VARCHAR2(200),
    NCRUCIAL    NUMBER(1) CONSTRAINT SHOP_NOTICE_NCRUCIAL_CHECK CHECK(NCRUCIAL IN(0,1)),
    NSDATE        VARCHAR2(10),
    NEDATE        VARCHAR2(10)
    );


--공지사항 시퀀스
CREATE SEQUENCE SEQU_MYSHOP_NOTICE
    START WITH 1
    INCREMENT BY 1 ;

--리뷰시퀀스
CREATE SEQUENCE sequ_MYSHOP_REVIEW
    START WITH 1
    INCREMENT BY 1 ;
select * from myshop_product;
--주문 시퀀스
CREATE SEQUENCE sequ_Myshop_ORDERS
    START WITH 1
    INCREMENT BY 1 ;

--주문데이터
insert into MYSHOP_ORDERS
values(500||sequ_myshop_orders.nextval,191,'admin','completed',sysdate,
'34672','대전 동구 판교1길 4빌딩','admin','LG','01047152584',
'대전 동구 판교1길 4빌딩',5,'125000');